### ISSUE TITLE
Adjust ratio_in and outs on the input file to base the throughput to electricity

### ISSUE THREAD

**Issue by sonercandas** [tum-ens/urbs#260]

**Comment by LT-2020** [comment]
I just stumbled over the same issue. 

I think, this is a very important issue, as this also influences the calculation of costs, if cost values are subject to output (MW_el) and not to input (e.g. MW_gas). And, actually, costs are usually related to output not input in general. So, the issue does not only apply ot electricity but to most commodities as well.

Probably, the issue is not too easy to cope with, as setting the main output to 1 implies that all other inputs and outputs must be relative to that (think of CO2_emissions, heat in a CHP plant,...) 

I would be interested in any plans to tackle this issue.
