### ISSUE TITLE
Time-dependent commodity prices

### ISSUE THREAD

**Issue by ojdo** [tum-ens/urbs#3]
Implement time-dependent prices for certain commodities. Instead of the constant price in attribute `Commodity:Site.Commodity.Type.price` (unit: money/quantity), have a price time series similar to the sheets *Demand* and *SupIm*.

**Rough implementation idea**
 - Define a non-numeric keyword (could be arbitrary) that could be placed into the price attribute, e.g. `eex`
 - If detected, an identically named column (e.g. `eex`) would need to exist in a spreadsheet *Price* that must conform to the same format as spreadsheet *Demand* with the time step identifiers in the first column.

**Open questions**
 - Possible implied work: ditch the "type" column of the commodity and simply derive the type[s] of a commodity from the properties that are or are not set in an input file.
 - Should negative prices be allowed? This implies export, which then would need a limiting attribute (or simply re-use `max` and `maxperstep`) if the commodity can be purchased.

At this stage, this proposal needs more thought before going to implementation.

**Comment by tzipperle** [comment]
Hi Johannes,

ich würde dir gerne meine Lösung hoch pushen. Das habe ich Leider noch nie gemacht. Wie ist da der beste Workflow?

Viele Grüße
Thomas

Von: Johannes Dorfner [mailto:notifications@github.com]
Gesendet: Freitag, 22. Mai 2015 10:31
An: tum-ens/urbs
Betreff: [urbs] Time-dependent commodity prices (#3)


Implement time-dependent prices for certain commodities. Instead of the constant price in attribute Commodity:Site.Commodity.Type.price (unit: money/quantity), have a price time series similar to the sheets Demand and SupIm.

Rough implementation idea

  *   Define a non-numeric keyword (could be arbitrary) that could be placed into the price attribute, e.g. eex
  *   If detected, an identically named column (e.g. eex) would need to exist in a spreadsheet Price that must conform to the same format as spreadsheet Demand with the time step identifiers in the first column.
  *

Open questions

  *   Possible implied work: ditch the "type" column of the commodity and simply derive the type[s] of a commodity from the properties that are or are not set in an input file.
  *   Should negative prices be allowed? This implies export, which then would need a limiting attribute (or simply re-use max and maxperstep) if the commodity can be purchased.

At this stage, this proposal needs more thought before going to implementation.

**Comment by ojdo** [comment]
Implemented in PR #14.
