### ISSUE TITLE
Rework/simplify rules that govern partial processes

### ISSUE THREAD

**Issue by ojdo** [tum-ens/urbs#82]
Right now, the rules for inclusion of processes in the tuple set `pro_partial_tuples`, which triggers the generation of all startup & partial process constraints, is triggered by the index set of the parameter `r_in_min_fraction`. It is currently formed by the following code fragment:

```
# input ratios for partial efficiencies
# only keep those entries whose values are
# a) positive and 
# b) numeric (implicitely, as NaN or NV compare false against 0) 
m.r_in_min_fraction = m.process_commodity.xs('In', level='Direction')['ratio-min']
m.r_in_min_fraction = m.r_in_min_fraction[m.r_in_min_fraction > 0]
```

Question 1: are these rules correct?
Question 2: how to document the trigger function of attribute `ratio-min`, and its widespread consequences for other attributes (`min-fraction` and `startup-cost` only make sense with a set `ratio-min`).

**Comment by KSchoenleber** [comment]
Concerning Q2: I already included some improvement into the mathematical documentation to make this point clear. My other suggestion is to also include a comment in this direction into the input file in the column description of 'ratio-min' which is currently empty.

Concerning Q1: it would probably be nice to be able to trigger the S&P features also with the r_out_min, since, e.g., in CHPs the partial behavior in heat and electricity output might change.

**Comment by lodersky** [comment]
Simplification is done in commit e5146ca03dcccc80cddbb591143000920d36a51d.

Documentation was rewritten in release 1.0.
